/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Header that contains the headers for which Rust Thermal bindings
 * will be automatically generated by `bindgen`.
 *
 * Sorted alphabetically.
 */

#include <linux/thermal.h>
